nodispatch: nodispatch.c
nodispatch-inline: nodispatch-inline.c
base: base.c
scarygoto: scarygoto.c
scarygoto-inline: scarygoto-inline.c
goto: goto.c
mgoto: mgoto.c
mgoto1: mgoto1.c
mgoto2: mgoto2.c
goto-direct: goto-direct.c
goto-direct2: goto-direct2.c
goto-direct3: goto-direct3.c
goto-direct-switch: goto-direct-switch.c
funcptr: funcptr.c
mdirect: mdirect.c
direct: direct.c
mfuncptr: mfuncptr.c
switch: switch.c
switch-direct: switch-direct.c
switch-direct-inline: switch-direct-inline.c
call-nodispatch: call-nodispatch.c
call-switch: call-switch.c

all:	nodispatch nodispatch-inline base goto mgoto mgoto1 mgoto2 \
	goto-direct goto-direct2 goto-direct3 goto-direct-switch funcptr mdirect \
	direct mfuncptr switch switch-direct switch-direct-inline \
	scarygoto scarygoto-inline call-nodispatch call-switch

clean:
	rm nodispatch nodispatch-inline base goto mgoto mgoto1 mgoto2 \
	goto-direct goto-direct2 goto-direct3 goto-direct-switch funcptr mdirect \
	direct mfuncptr switch switch-direct switch-direct-inline \
	scarygoto scarygoto-inline call-nodispatch call-switch
